import { GenesisBlock } from '../../resource'

const proposerNames = [
    'Andrew Kim',
    'Andy Shin',
    'Austin Brown',
    'Bongtae Yun',
    'Bora Kang',
    'Boyoung Kim',
    'Byungchul Lee',
    'Choah Jung',
    'Christine Lee',
    'Daewoo Cho',
    'Donghwan Kwon',
    'Dongju Lee',
    'Eric Kim',
    'Euiyoul Kim',
    'Goun Kwak',
    'Kuwon Ra',
    'Gwangil Won',
    'HeeJae Myoung',
    'Hosung Han',
    'Hoyoung Kang',
    'Hyewon Lim',
    'Hyojin Oh',
    'Hyung-Kyu Choi',
    'Hyunjin Lee',
    'Hyunmin Han',
    'Ian Park',
    'Ire Song',
    'Jaesun Han',
    'Jaewon Han',
    'Jaewoo Lee',
    'Jensen Yap',
    'Jeongho Nah',
    'Jeongkyun Oh',
    'Ji Sung Lim',
    'Jiehwan Song',
    'Jieun Kim',
    'JiEun Lee',
    'Jimin Kim',
    'Jina Kim',
    'Jinhun Shin',
    'Jiwon Bae',
    'Jiwon Ryu',
    'John Cho',
    'Jong Gun Lee',
    'Jonghui Lee',
    'Joonsung Lee',
    'Joseph Hung',
    'Ju Hye Kim',
    'Junghun Hur',
    'Junghyun Kim',
    'Junghyun Lee',
    'Junhee Woo',
    'Junho Cho',
    'Junsic Youn',
    'KiJun Sung',
    'Kyung Tae No',
    'KyungKoo Kim',
    'Kyungup Kim',
    'Mi Jeong Park',
    'Minjae Lee',
    'Minjee Kim',
    'Minsu Kim',
    'Myeongjin Jeong',
    'Namseok Baek',
    'Sangeon Bae',
    'Sangmin Seo',
    'Sean Kim',
    'Seonghwan Cho',
    'Seungchan Shin',
    'Siho Choue',
    'Sojin Kim',
    'Soo Hwan Kim',
    'Soon Il Hong',
    'SukEui Lim',
    'Taekeun Kim',
    'Uno Lee',
    'Woojin Lee',
    'Yeehyun Chun',
    'Yeolmae Kim',
    'Yerang Park',
    'YG Kang',
    'Yirey Suh',
    'Yongho Choi',
    'YongJoon Kim',
    'Yoshi Shin',
    'Youngjun Lim',
    'Youngkyu Park',
    'Youngmin Park',
    'Yuna Noh',
    'Yunsuk Seo',
    'Yuntaek Lim',
    'Zachary Keats',
].join(', ')

export const genesisBlock: GenesisBlock = {
    proposerNames,
    blockSize: 1392,
    hash: '0xc72e5293c3c3ba38ed8ae910f780e4caaa9fb95e79784f7ab74c3c262ea7137e',
    datetime: '2019-06-24T12:45:05.305Z',
    filepath: '/resources/finder/genesis_block.jpg',
}
