name: finder-deploy
on:
    workflow_dispatch:
        inputs:
            target:
                description: 'Target Phase'
                required: true
                default: 'stage'
                type: choice
                options:
                    - dev
                    - stage
                    - prod

concurrency:
    group: finder-deploy-${{ github.event.inputs.target }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2

            - name: Set NodeJS version
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/

            - name: Cache npm dependencies
              uses: actions/cache@v3
              env:
                  cache-name: npm-cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install dependencies
              run: npm install

            - name: ENV setting
              if: ${{ inputs.target == 'prod' }}
              run: |
                  echo "GENERATE_SOURCEMAP=false" >> $GITHUB_ENV

            - name: Build
              env:
                  REACT_APP_GIT_HASH: ${{ github.sha }}
                  REACT_APP_SERVICE: finder
              run: npm run build:finder

            - name: Cache build result
              uses: actions/cache@v3
              env:
                  cache-name: cache-build-result
              with:
                  path: ./
                  key: build-${{ github.sha }}-${{ inputs.target }}-finder

    deploy:
        # runs-on: [self-hosted, linux]
        runs-on: ubuntu-latest
        needs: [build]
        strategy:
            matrix:
                network: [cypress, baobab]
        steps:
            - name: Set NodeJS version
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/

            - name: ENV setting for dev
              if: ${{ inputs.target == 'dev' }}
              run: |
                  echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
                  echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
                  echo "AWS_S3_BUCKET_HOST=s3://klaytn-dev-finder-public/web" >> $GITHUB_ENV
                  echo "S3_SYNC_OPTION=--delete" >> $GITHUB_ENV

            - name: ENV setting for stage
              if: ${{ inputs.target == 'stage' }}
              run: |
                  echo "AWS_ACCESS_KEY=${{ secrets.PROD_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
                  echo "AWS_SECRET_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
                  echo "AWS_S3_BUCKET_HOST=s3://klaytn-prod-finder-public/web-stage" >> $GITHUB_ENV
                  echo "S3_SYNC_OPTION=--delete" >> $GITHUB_ENV

            - name: ENV setting for prod
              if: ${{ inputs.target == 'prod' }}
              run: |
                  echo "AWS_ACCESS_KEY=${{ secrets.PROD_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
                  echo "AWS_SECRET_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
                  echo "AWS_S3_BUCKET_HOST=s3://klaytn-prod-finder-public/web" >> $GITHUB_ENV
                  echo "S3_SYNC_OPTION=" >> $GITHUB_ENV

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
                  aws-region: ap-northeast-2

            - name: Cache build result
              uses: actions/cache@v3
              env:
                  cache-name: cache-build-result
              with:
                  path: ./
                  key: build-${{ github.sha }}-${{ inputs.target }}-finder

            - name: Install build scripts dependencies
              run: npm install -g ts-node turbo

            - name: Create config file
              env:
                  REACT_APP_GIT_HASH: ${{ github.sha }}
                  REACT_APP_NETWORK: ${{ matrix.network }}
                  REACT_APP_TARGET: ${{ inputs.target }}
                  REACT_APP_ACCESS_KEY: ${{ secrets.FINDER_ACCESS_KEY }}
                  REACT_APP_SECRET_KEY: ${{ secrets.FINDER_SECRET_KEY }}
                  REACT_APP_GA_ID: ${{ secrets.REACT_APP_GA_ID }}
                  REACT_APP_RUM_APPLICAION_ID: ${{ secrets.REACT_APP_RUM_APPLICAION_ID }}
                  REACT_APP_RUM_CLIENT_TOKEN: ${{ secrets.REACT_APP_RUM_CLIENT_TOKEN }}
              run: ts-node ./scripts/createConfig.ts "./build"
              working-directory: ./apps/finder

            - name: Upload to S3
              run: aws s3 sync ./build ${{ env.AWS_S3_BUCKET_HOST }}/${{ matrix.network }} ${{ env.S3_SYNC_OPTION }}
              working-directory: ./apps/finder

    invalidate-for-prod:
        # runs-on: [self-hosted, linux]
        runs-on: ubuntu-latest
        needs: [deploy]
        if: ${{ inputs.target == 'prod' }}
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-northeast-2

            - name: Invalidation CDN cache
              run: |
                  aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_FINDER_DISTRIBUTION_ID_CYPRESS_PROD }} --paths "/index.html"
                  aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_FINDER_DISTRIBUTION_ID_BAOBAB_PROD }} --paths "/index.html"
