name: deploy-slush-storybook
on:
    push:
        branches: [main]
        paths:
            - 'packages/slush/**/*'
    workflow_dispatch:
concurrency:
    group: deploy-slush-storybook
    cancel-in-progress: true
jobs:
    deploy:
        strategy:
            matrix:
                node-version: [16.x]

        # runs-on: [self-hosted, linux]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2

            - name: Set NodeJS version
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/

            - name: Cache npm dependencies
              uses: actions/cache@v1
              id: npm-cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build:slush:storybook

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./packages/slush/storybook-static
