# name: slush-version-update-check
# on:
#     pull_request:
#         types: [opened, reopened, synchronize]
#         branches: [main]
#         paths:
#             - 'packages/slush/**/*'

# concurrency:
#     group: slush-version-update-check
#     cancel-in-progress: true

# jobs:
#     version-check:
#         runs-on: [self-hosted, linux]
#         steps:
#             - name: Checkout source code
#               uses: actions/checkout@v2

#             - name: Check version
#               id: check
#               uses: EndBug/version-check@v1
#               with:
#                   diff-search: true
#                   file-name: ./packages/slush/package.json
#                   token: ${{ secrets.REPO_ACCESS_TOKEN }}

#             - name: Log when changed
#               if: steps.check.outputs.changed == 'true'
#               run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }}"'

#             - name: Log when unchanged
#               if: steps.check.outputs.changed != 'true'
#               uses: actions/github-script@v3
#               with:
#                   script: |
#                       core.setFailed('No version change')
